# Data Loading: DBPedia Dataset

Data source: https://github.com/marius92mc/document-classification-reuters21578/tree/master

## Setup

In [1]:
# Check Python version
!python --version

Python 3.13.9

In [2]:
# %pip install torch==2.9.1 torchvision --index-url https://download.pytorch.org/whl/cu128

In [3]:
# Load / save the list of installed libraries
# !pip freeze > new_requirements.txt
# %pip install -r my_requirements.txt

In [2]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:
# Set CUDA_VISIBLE_DEVICES before importing torch
seed = 42

np.random.seed(seed)
os.environ['PYTHONHASHSEED'] = str(seed)
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

## Handle input data

In [4]:
splits = {'train': 'DBPEDIA_train.csv', 'validation': 'DBPEDIA_val.csv', 'test': 'DBPEDIA_test.csv'}
df_train = pd.read_csv("hf://datasets/DeveloperOats/DBPedia_Classes/" + splits["train"])
df_validation = pd.read_csv("hf://datasets/DeveloperOats/DBPedia_Classes/" + splits["validation"])
df_test = pd.read_csv("hf://datasets/DeveloperOats/DBPedia_Classes/" + splits["test"])

In [ ]:
df_train.to_csv("data/raw/dbpedia_train.csv", index=False)

In [5]:
df_train

,text,l1,l2,l3
0,"William Alexander Massey (October 7, 1856 – Ma...",Agent,Politician,Senator
1,Lions is the sixth studio album by American ro...,Work,MusicalWork,Album
2,"Pirqa (Aymara and Quechua for wall, hispaniciz...",Place,NaturalPlace,Mountain
3,Cancer Prevention Research is a biweekly peer-...,Work,PeriodicalLiterature,AcademicJournal
4,The Princeton University Chapel is located on ...,Place,Building,HistoricBuilding
...,...,...,...,...
240937,Charlie Thompson is a prominent journalist in ...,Agent,Person,Journalist
240938,The Northerly Stakes is a Perth Racing Group 3...,Event,Race,HorseRace
240939,HC Empor Rostock is a team handball club from ...,Agent,SportsTeam,HandballTeam
240940,University of Surabaya (UBAYA) is a university...,Agent,EducationalInstitution,University
240941,The 1981 Seattle Seahawks season was the team'...,SportsSeason,FootballLeagueSeason,NationalFootballLeagueSeason

In [6]:
df_train['text'][31238]

"Mount Hubbard is one of the major mountains of the Saint Elias Range. It is located on the Alaska/Yukon border; the Canadian side is within Kluane National Park and Reserve, and the American side is part of Wrangell–St. Elias National Park. The mountain was named in 1890 by U.S. Geological Survey geologist Israel Russell after Gardiner Greene Hubbard, first president of the National Geographic Society, which had co-sponsored Russell's expedition. Hubbard is the highest point of a large massif with three named summits; the other two are Mount Alverstone and Mount Kennedy. Alverstone and Hubbard form a corner of the Canada–United States border: the border extends roughly south from these peaks toward the Alaska panhandle, and roughly west toward Mount Saint Elias, approximately 100 km (62 mi) away. The Hubbard Glacier separates Mount Hubbard from Mount Vancouver to the west, while the Lowell Glacier lies to the east of the peak. Mount Hubbard is the eighth-highest peak in the United States, and the twelfth-highest peak in Canada. It is also notable for its large rise above local terrain. For example, its west face rises 7,500 feet (2,300 meters) above the Alverstone Glacier in less than 2 miles (3.2 kilometers), and the peak rises 11,000 feet (3,350 m) above the Hubbard Glacier to the southwest in only 7 mi (11.3 km). Mount Hubbard is just over 20 mi (32 km) from tidewater at Disenchantment Bay. However, despite its precipitous drops to the west, the eastern side provides a non-technical (though long) route to the summit."

In [15]:
df_all = pd.concat([df_train, df_validation, df_test], ignore_index=True)

df_all

,text,l1,l2,l3
0,"William Alexander Massey (October 7, 1856 – Ma...",Agent,Politician,Senator
1,Lions is the sixth studio album by American ro...,Work,MusicalWork,Album
2,"Pirqa (Aymara and Quechua for wall, hispaniciz...",Place,NaturalPlace,Mountain
3,Cancer Prevention Research is a biweekly peer-...,Work,PeriodicalLiterature,AcademicJournal
4,The Princeton University Chapel is located on ...,Place,Building,HistoricBuilding
...,...,...,...,...
337734,Darwin Smith was CEO of Kimberly-Clark from 19...,Agent,Person,BusinessPerson
337735,The HKRU Premiership is the main domestic comp...,Agent,SportsLeague,SoccerLeague
337736,"Leo Harvey Diegel (April 20, 1899 – May 5, 195...",Agent,Athlete,GolfPlayer
337737,"Clement Reginald \""Clem\"" Splatt (17 September...",Agent,Athlete,AustralianRulesFootballPlayer
337738,Gyllebo Castle (Swedish: Gyllebo slott) is a c...,Place,Building,Castle

In [16]:
# Save dataframe to .csv file
df_all.to_csv('raw/dbpedia_all.csv', index=False)

In [17]:
df = df_all

In [18]:
# Drop rows where 'body' is missing or empty
df = df.dropna(subset=['text'])
df = df[df['text'].astype(str).str.strip() != '']
dataset = df
display(dataset.head())
print('DataFrame shape:', dataset.shape)

,text,l1,l2,l3
0,"William Alexander Massey (October 7, 1856 – Ma...",Agent,Politician,Senator
1,Lions is the sixth studio album by American ro...,Work,MusicalWork,Album
2,"Pirqa (Aymara and Quechua for wall, hispaniciz...",Place,NaturalPlace,Mountain
3,Cancer Prevention Research is a biweekly peer-...,Work,PeriodicalLiterature,AcademicJournal
4,The Princeton University Chapel is located on ...,Place,Building,HistoricBuilding

DataFrame shape: (337739, 4)

In [19]:
df = df.drop_duplicates(subset=['text']).reset_index(drop=True)

df

,text,l1,l2,l3
0,"William Alexander Massey (October 7, 1856 – Ma...",Agent,Politician,Senator
1,Lions is the sixth studio album by American ro...,Work,MusicalWork,Album
2,"Pirqa (Aymara and Quechua for wall, hispaniciz...",Place,NaturalPlace,Mountain
3,Cancer Prevention Research is a biweekly peer-...,Work,PeriodicalLiterature,AcademicJournal
4,The Princeton University Chapel is located on ...,Place,Building,HistoricBuilding
...,...,...,...,...
337734,Darwin Smith was CEO of Kimberly-Clark from 19...,Agent,Person,BusinessPerson
337735,The HKRU Premiership is the main domestic comp...,Agent,SportsLeague,SoccerLeague
337736,"Leo Harvey Diegel (April 20, 1899 – May 5, 195...",Agent,Athlete,GolfPlayer
337737,"Clement Reginald \""Clem\"" Splatt (17 September...",Agent,Athlete,AustralianRulesFootballPlayer
337738,Gyllebo Castle (Swedish: Gyllebo slott) is a c...,Place,Building,Castle

In [20]:
# Save dataframe to .csv file
df.to_csv('complete/dbpedia.csv', index=False)

In [ ]:
# Processing with data_cleaning.py

In [21]:
df_text = pd.read_parquet(f'processed/parquet/dbpedia_text.parquet')

In [22]:
df_text

                                                     text
0       William Alexander Massey (October 7, 1856 – Ma...
1       Lions is the sixth studio album by American ro...
2       Pirqa (Aymara and Quechua for wall, hispaniciz...
3       Cancer Prevention Research is a biweekly peer-...
4       The Princeton University Chapel is located on ...
...                                                   ...
337734  Darwin Smith was CEO of Kimberly-Clark from 19...
337735  The HKRU Premiership is the main domestic comp...
337736  Leo Harvey Diegel (April 20, 1899 – May 5, 195...
337737  Clement Reginald "Clem" Splatt (17 September 1...
337738  Gyllebo Castle (Swedish: Gyllebo slott) is a c...

[337739 rows x 1 columns]

In [23]:
# Print dataset statistics
avg_chars = df_text['text'].apply(lambda x: len(str(x))).mean()
print("Average number of characters for text passage:", avg_chars)
avg_words = df_text['text'].apply(lambda x: len(x.split(" "))).mean()
print("Average number of words for text passage:", avg_words)
print("Average word length:", avg_chars / avg_words)

Average number of characters for text passage: 625.733806282366
Average number of words for text passage: 102.75500312371388
Average word length: 6.089570213228466

In [24]:
# Convert 'text' column into list containing documents
docs = df_text['text'].tolist()

In [25]:
# Ensure all documents are strings
for i in range(len(docs)):
    docs[i] = str(docs[i])

In [26]:
# Print length of the document list
print("Number of documents:", len(docs))

Number of documents: 337739

In [27]:
# Print a sample of document
print(docs[9])

The International Association of Plumbing and Mechanical Officials, or IAPMO, coordinates the development and adaptation of plumbing, mechanical, swimming pool and solar energy codes to meet the specific needs of individual jurisdictions both in the United States and abroad. IAPMO develops and publishes the Uniform Plumbing Code (UPC); Uniform Mechanical Code (UMC); Uniform Swimming Pool, Spa and Hot Tub Code (USPSHTC); Uniform Solar Energy Code (USEC); and the Green Plumbing and Mechanical Code Supplement (GPMCS).