# Data Loading: Reuters-21578 Dataset

Data source: https://github.com/marius92mc/document-classification-reuters21578/tree/master

## Setup

In [1]:
# Check Python version
!python --version

Python 3.13.9

In [3]:
# %pip install torch==2.9.1 torchvision --index-url https://download.pytorch.org/whl/cu128

In [4]:
# Load / save the list of installed libraries
# !pip freeze > new_requirements.txt
# %pip install -r my_requirements.txt

In [4]:
# Import libraries
import numpy as np
import pandas as pd
import re
import os

In [5]:
# Set CUDA_VISIBLE_DEVICES before importing torch
seed = 42

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
os.environ['PYTHONHASHSEED'] = str(seed)
np.random.seed(seed)

## Handle input data

In [6]:
# Import libraries
import json
from pathlib import Path
from pandas import json_normalize

In [7]:
# Combine .json files into a DataFrame
data_dir = Path('raw/reuters21578/json') 
files = sorted(data_dir.glob('**/*.json'))
print(f'Found {len(files)} json files in {data_dir}')
records = []
for fp in files:
    try:
        with fp.open('r', encoding='utf-8') as fh:
            obj = json.load(fh)
        # Support files that contain a list of objects or a single object
        if isinstance(obj, list):
            records.extend(obj)
        elif isinstance(obj, dict):
            records.append(obj)
        else:
            # skip non-dict/list payloads
            print(f'skipped (unexpected type) {fp}')
    except Exception as e:
        print(f'error reading {fp}: {e}')

print(f'Collected {len(records)} records')
if len(records) == 0:
    df = pd.DataFrame()
else:
    # normalize nested JSON into flat table where possible
    df = json_normalize(records)

print('DataFrame shape:', df.shape)
display(df.head())

Found 22 json files in raw\reuters21578\json
Collected 21578 records
DataFrame shape: (21578, 7)

,title,body,date,topics,places,id,organisations
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,26-FEB-1987 15:01:01.79,[cocoa],"[el-salvador, usa, uruguay]",1,NaN
1,STANDARD OIL <SRD> TO FORM FINANCIAL UNIT,Standard Oil Co and BP North America\nInc said...,26-FEB-1987 15:02:20.00,NaN,[usa],2,NaN
2,TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN,Texas Commerce Bancshares Inc's Texas\nCommerc...,26-FEB-1987 15:03:27.51,NaN,[usa],3,NaN
3,TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER,BankAmerica Corp is not under\npressure to act...,26-FEB-1987 15:07:13.72,NaN,"[usa, brazil]",4,NaN
4,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,26-FEB-1987 15:10:44.60,"[grain, wheat, corn, barley, oat, sorghum]",[usa],5,NaN

In [8]:
df = df.rename(columns={'body': 'text'})

df

,title,text,date,topics,places,id,organisations
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,26-FEB-1987 15:01:01.79,[cocoa],"[el-salvador, usa, uruguay]",1,NaN
1,STANDARD OIL <SRD> TO FORM FINANCIAL UNIT,Standard Oil Co and BP North America\nInc said...,26-FEB-1987 15:02:20.00,NaN,[usa],2,NaN
2,TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN,Texas Commerce Bancshares Inc's Texas\nCommerc...,26-FEB-1987 15:03:27.51,NaN,[usa],3,NaN
3,TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER,BankAmerica Corp is not under\npressure to act...,26-FEB-1987 15:07:13.72,NaN,"[usa, brazil]",4,NaN
4,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,26-FEB-1987 15:10:44.60,"[grain, wheat, corn, barley, oat, sorghum]",[usa],5,NaN
...,...,...,...,...,...,...,...
21573,JAPAN/INDIA CONFERENCE CUTS GULF WAR RISK CHARGES,The Japan/India-Pakistan-Gulf/Japan\nshipping ...,19-OCT-1987 00:34:08.94,[ship],"[hong-kong, japan, india, pakistan, iran, iraq]",21574,NaN
21574,SOVIET INDUSTRIAL GROWTH/TRADE SLOWER IN 1987,The Soviet Union's industrial output is\ngrowi...,19-OCT-1987 00:18:22.79,[ipi],[ussr],21575,NaN
21575,SIX KILLED IN SOUTH AFRICAN GOLD MINE ACCIDENT,Six black miners have been killed\nand two inj...,19-OCT-1987 00:05:11.26,[gold],[south-africa],21576,NaN
21576,PROJECTIONS SHOW SWISS VOTERS WANT TRIED PARTIES,The prospect of a dominant alliance of\nsocial...,19-OCT-1987 00:03:21.69,NaN,[switzerland],21577,NaN
21577,AMERICAN EXCHANGE INTRODUCES INSTITUTIONAL INDEX,The American Stock Exchange said it has\nintro...,19-OCT-1987 13:30:41.59,NaN,[usa],21578,NaN

In [9]:
df.to_csv('raw/reuters21578.csv', index=False)

In [10]:
# Drop rows where 'text' is missing or empty
df = df.dropna(subset=['text']).reset_index(drop=True)
df = df[df['text'].astype(str).str.strip() != '']
dataset = df
display(dataset.head())
print('DataFrame shape:', dataset.shape)

,title,text,date,topics,places,id,organisations
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,26-FEB-1987 15:01:01.79,[cocoa],"[el-salvador, usa, uruguay]",1,NaN
1,STANDARD OIL <SRD> TO FORM FINANCIAL UNIT,Standard Oil Co and BP North America\nInc said...,26-FEB-1987 15:02:20.00,NaN,[usa],2,NaN
2,TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN,Texas Commerce Bancshares Inc's Texas\nCommerc...,26-FEB-1987 15:03:27.51,NaN,[usa],3,NaN
3,TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER,BankAmerica Corp is not under\npressure to act...,26-FEB-1987 15:07:13.72,NaN,"[usa, brazil]",4,NaN
4,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,26-FEB-1987 15:10:44.60,"[grain, wheat, corn, barley, oat, sorghum]",[usa],5,NaN

DataFrame shape: (19043, 7)

In [ ]:
# df.to_csv('raw/reuters_drop_na.csv', index=False)

In [12]:
df_drop_na_topics = df.dropna(subset=['topics']).reset_index(drop=True)

df_drop_na_topics

,title,text,date,topics,places,id,organisations
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,26-FEB-1987 15:01:01.79,[cocoa],"[el-salvador, usa, uruguay]",1,NaN
1,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,26-FEB-1987 15:10:44.60,"[grain, wheat, corn, barley, oat, sorghum]",[usa],5,NaN
2,ARGENTINE 1986/87 GRAIN/OILSEED REGISTRATIONS,Argentine grain board figures show\ncrop regis...,26-FEB-1987 15:14:36.41,"[veg-oil, linseed, lin-oil, soy-oil, sun-oil, ...",[argentina],6,NaN
3,CHAMPION PRODUCTS <CH> APPROVES STOCK SPLIT,Champion Products Inc said its\nboard of direc...,26-FEB-1987 15:17:11.20,[earn],[usa],9,NaN
4,COMPUTER TERMINAL SYSTEMS <CPML> COMPLETES SALE,Computer Terminal Systems Inc said\nit has com...,26-FEB-1987 15:18:06.67,[acq],[usa],10,NaN
...,...,...,...,...,...,...,...
10372,N.Z.'S CHASE CORP MAKES OFFER FOR ENTREGROWTH,Chase Corp Ltd <CHCA.WE> said it will\nmake an...,19-OCT-1987 01:35:27.64,[acq],[new-zealand],21571,NaN
10373,TOKYO DEALERS SEE DOLLAR POISED TO BREACH 140 YEN,Tokyo's foreign exchange market is watching\nn...,19-OCT-1987 00:59:58.56,"[money-fx, dlr, yen]","[japan, west-germany, usa]",21573,NaN
10374,JAPAN/INDIA CONFERENCE CUTS GULF WAR RISK CHARGES,The Japan/India-Pakistan-Gulf/Japan\nshipping ...,19-OCT-1987 00:34:08.94,[ship],"[hong-kong, japan, india, pakistan, iran, iraq]",21574,NaN
10375,SOVIET INDUSTRIAL GROWTH/TRADE SLOWER IN 1987,The Soviet Union's industrial output is\ngrowi...,19-OCT-1987 00:18:22.79,[ipi],[ussr],21575,NaN
10376,SIX KILLED IN SOUTH AFRICAN GOLD MINE ACCIDENT,Six black miners have been killed\nand two inj...,19-OCT-1987 00:05:11.26,[gold],[south-africa],21576,NaN

In [13]:
df_drop_na_topics = df_drop_na_topics.drop_duplicates(subset=['text']).reset_index(drop=True)

df_drop_na_topics

,title,text,date,topics,places,id,organisations
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,26-FEB-1987 15:01:01.79,[cocoa],"[el-salvador, usa, uruguay]",1,NaN
1,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,26-FEB-1987 15:10:44.60,"[grain, wheat, corn, barley, oat, sorghum]",[usa],5,NaN
2,ARGENTINE 1986/87 GRAIN/OILSEED REGISTRATIONS,Argentine grain board figures show\ncrop regis...,26-FEB-1987 15:14:36.41,"[veg-oil, linseed, lin-oil, soy-oil, sun-oil, ...",[argentina],6,NaN
3,CHAMPION PRODUCTS <CH> APPROVES STOCK SPLIT,Champion Products Inc said its\nboard of direc...,26-FEB-1987 15:17:11.20,[earn],[usa],9,NaN
4,COMPUTER TERMINAL SYSTEMS <CPML> COMPLETES SALE,Computer Terminal Systems Inc said\nit has com...,26-FEB-1987 15:18:06.67,[acq],[usa],10,NaN
...,...,...,...,...,...,...,...
10247,N.Z.'S CHASE CORP MAKES OFFER FOR ENTREGROWTH,Chase Corp Ltd <CHCA.WE> said it will\nmake an...,19-OCT-1987 01:35:27.64,[acq],[new-zealand],21571,NaN
10248,TOKYO DEALERS SEE DOLLAR POISED TO BREACH 140 YEN,Tokyo's foreign exchange market is watching\nn...,19-OCT-1987 00:59:58.56,"[money-fx, dlr, yen]","[japan, west-germany, usa]",21573,NaN
10249,JAPAN/INDIA CONFERENCE CUTS GULF WAR RISK CHARGES,The Japan/India-Pakistan-Gulf/Japan\nshipping ...,19-OCT-1987 00:34:08.94,[ship],"[hong-kong, japan, india, pakistan, iran, iraq]",21574,NaN
10250,SOVIET INDUSTRIAL GROWTH/TRADE SLOWER IN 1987,The Soviet Union's industrial output is\ngrowi...,19-OCT-1987 00:18:22.79,[ipi],[ussr],21575,NaN
10251,SIX KILLED IN SOUTH AFRICAN GOLD MINE ACCIDENT,Six black miners have been killed\nand two inj...,19-OCT-1987 00:05:11.26,[gold],[south-africa],21576,NaN

In [14]:
df_drop_na_topics.to_csv('complete/reuters.csv', index=False)

In [17]:
# Processing with data_cleaning.py

In [18]:
df_text = pd.read_parquet(f'processed/parquet/reuters_text.parquet')

In [19]:
df_text

                                                    text
0      Showers continued throughout the week in the B...
1      The U.S. Agriculture Department reported the f...
2      Argentine grain board figures show crop regist...
3      Champion Products Inc said its board of direct...
4      Computer Terminal Systems Inc said it has comp...
...                                                  ...
10247  Chase Corp Ltd <CHCA.WE> said it will make an ...
10248  Tokyo's foreign exchange market is watching ne...
10249  The Japan/India-Pakistan-Gulf/Japan shipping c...
10250  The Soviet Union's industrial output is growin...
10251  Six black miners have been killed and two inju...

[10252 rows x 1 columns]

In [20]:
# Print dataset statistics
avg_chars = df_text['text'].apply(lambda x: len(str(x))).mean()
print("Average number of characters for text passage:", avg_chars)
avg_words = df_text['text'].apply(lambda x: len(x.split(" "))).mean()
print("Average number of words for text passage:", avg_words)
print("Average word length:", avg_chars / avg_words)

Average number of characters for text passage: 797.0564767850176
Average number of words for text passage: 133.72327350760827
Average word length: 5.960491811768791

In [21]:
# Convert 'body' column into list containing documents
docs = df_text['text'].tolist()

In [22]:
# Ensure all documents are strings
for i in range(len(docs)):
    docs[i] = str(docs[i])

In [23]:
# Print length of the document list
print("Number of documents:", len(docs))

Number of documents: 10252

In [24]:
# Print a sample of document
print(docs[9])

Dean Foods Co expects earnings for the fourth quarter ending May 30 to exceed those of the same year-ago period, Chairman Kenneth Douglas told analysts. In the fiscal 1986 fourth quarter the food processor reported earnings of 40 cts a share. Douglas also said the year's sales should exceed 1.4 billion dlrs, up from 1.27 billion dlrs the prior year. He repeated an earlier projection that third-quarter earnings "will probably be off slightly" from last year's 40 cts a share, falling in the range of 34 cts to 36 cts a share. Douglas said it was too early to project whether the anticipated fourth quarter performance would be "enough for us to exceed the prior year's overall earnings" of 1.53 dlrs a share. In 1988, Douglas said Dean should experience "a 20 pct improvement in our bottom line from effects of the tax reform act alone." President Howard Dean said in fiscal 1988 the company will derive benefits of various dairy and frozen vegetable acquisitions from Ryan Milk to the Larsen Co. Dean also said the company will benefit from its acquisition in late December of Elgin Blenders Inc, West Chicago. He said the company is a major shareholder of E.B.I. Foods Ltd, a United Kingdom blender, and has licensing arrangements in Australia, Canada, Brazil and Japan. "It provides ann entry to McDonalds Corp <MCD> we've been after for years," Douglas told analysts.

In [9]:
import ast

In [10]:
# Create a safe conversion function
def safe_convert(val):
    # If it's already a list, just return it
    if isinstance(val, list):
        return val
    # If it's empty/NaN, return an empty list (which tomotopy needs for unlabeled data)
    if pd.isna(val) or val == "":
        return []
    # Otherwise, safely evaluate the string
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        # Fallback just in case the string is malformed
        return []

In [11]:
df['topics'] = df['topics'].apply(safe_convert)

In [13]:
labels_df = df[['topics']]

labels_df

                                                  topics
0                                                [cocoa]
1             [grain, wheat, corn, barley, oat, sorghum]
2      [veg-oil, linseed, lin-oil, soy-oil, sun-oil, ...
3                                                 [earn]
4                                                  [acq]
...                                                  ...
10372                                              [acq]
10373                               [money-fx, dlr, yen]
10374                                             [ship]
10375                                              [ipi]
10376                                             [gold]

[10377 rows x 1 columns]

In [14]:
labels_df = labels_df.rename(columns={'topics': 'labels'})

labels_df

                                                  labels
0                                                [cocoa]
1             [grain, wheat, corn, barley, oat, sorghum]
2      [veg-oil, linseed, lin-oil, soy-oil, sun-oil, ...
3                                                 [earn]
4                                                  [acq]
...                                                  ...
10372                                              [acq]
10373                               [money-fx, dlr, yen]
10374                                             [ship]
10375                                              [ipi]
10376                                             [gold]

[10377 rows x 1 columns]

In [29]:
labels_df.to_parquet('processed/reuters_drop_na_topics_labels.parquet', index=False)

In [75]:
df_clean['text'] = df_clean['text'].astype(str)

C:\Users\zheng\AppData\Local\Temp\ipykernel_23396\2758870227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['text'] = df_clean['text'].astype(str)

In [38]:
df_remove_na_topics = df_to_save.dropna(subset=['topics'])

df_remove_na_topics

,text,topics
0,Showers continued throughout the week in\nthe ...,[cocoa]
4,The U.S. Agriculture Department\nreported the ...,"[grain, wheat, corn, barley, oat, sorghum]"
5,Argentine grain board figures show\ncrop regis...,"[veg-oil, linseed, lin-oil, soy-oil, sun-oil, ..."
8,Champion Products Inc said its\nboard of direc...,[earn]
9,Computer Terminal Systems Inc said\nit has com...,[acq]
...,...,...
21570,Chase Corp Ltd <CHCA.WE> said it will\nmake an...,[acq]
21572,Tokyo's foreign exchange market is watching\nn...,"[money-fx, dlr, yen]"
21573,The Japan/India-Pakistan-Gulf/Japan\nshipping ...,[ship]
21574,The Soviet Union's industrial output is\ngrowi...,[ipi]
21575,Six black miners have been killed\nand two inj...,[gold]

In [39]:
df_remove_na_topics.to_csv('reuters_no_na_topics.csv', index=False)

In [16]:
# Count documents with missing topics
df['topics'].isnull().sum()

np.int64(8666)

In [17]:
# Count documents with missing organisations
df['organisations'].isnull().sum()

np.int64(18189)

In [18]:
# Print dataset statistics
avg_chars = dataset['body'].apply(lambda x: len(str(x))).mean()
print("Average number of characters for text passage:", avg_chars)
avg_words = dataset['body'].apply(lambda x: len(x.split(" "))).mean()
print("Average number of words for text passage:", avg_words)
print("Average word length:", avg_chars / avg_words)

Average number of characters for text passage: 836.4228850496245
Average number of words for text passage: 139.83101402090006
Average word length: 5.981669309246426

In [19]:
# Convert 'body' column into list containing documents
docs = dataset['body'].tolist()

In [20]:
# Ensure all documents are strings
for i in range(len(docs)):
    docs[i] = str(docs[i])

In [21]:
# Print length of the document list
print("Number of documents:", len(docs))

Number of documents: 19043

In [22]:
# Print a sample of document
print(docs[9])

Computer Terminal Systems Inc said
it has completed the sale of 200,000 shares of its common
stock, and warrants to acquire an additional one mln shares, to
<Sedio N.V.> of Lugano, Switzerland for 50,000 dlrs.
    The company said the warrants are exercisable for five
years at a purchase price of .125 dlrs per share.
    Computer Terminal said Sedio also has the right to buy
additional shares and increase its total holdings up to 40 pct
of the Computer Terminal's outstanding common stock under
certain circumstances involving change of control at the
company.
    The company said if the conditions occur the warrants would
be exercisable at a price equal to 75 pct of its common stock's
market price at the time, not to exceed 1.50 dlrs per share.
    Computer Terminal also said it sold the technolgy rights to
its Dot Matrix impact technology, including any future
improvements, to <Woodco Inc> of Houston, Tex. for 200,000
dlrs. But, it said it would continue to be the exclusive
worldwide licensee of the technology for Woodco.
    The company said the moves were part of its reorganization
plan and would help pay current operation costs and ensure
product delivery.
    Computer Terminal makes computer generated labels, forms,
tags and ticket printers and terminals.
 Reuter


In [23]:
# Load dataframe from .csv file
df_new = pd.read_csv('reuters21578.csv')

df_new.head()

,title,body,date,topics,places,id,organisations
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,26-FEB-1987 15:01:01.79,['cocoa'],"['el-salvador', 'usa', 'uruguay']",1,NaN
1,STANDARD OIL <SRD> TO FORM FINANCIAL UNIT,Standard Oil Co and BP North America\nInc said...,26-FEB-1987 15:02:20.00,NaN,['usa'],2,NaN
2,TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN,Texas Commerce Bancshares Inc's Texas\nCommerc...,26-FEB-1987 15:03:27.51,NaN,['usa'],3,NaN
3,TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER,BankAmerica Corp is not under\npressure to act...,26-FEB-1987 15:07:13.72,NaN,"['usa', 'brazil']",4,NaN
4,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,26-FEB-1987 15:10:44.60,"['grain', 'wheat', 'corn', 'barley', 'oat', 's...",['usa'],5,NaN

In [24]:
df_new.shape

(19043, 7)

In [31]:
reuters_drop_na = pd.read_csv('processed/reuters_drop_na.csv')

reuters_drop_na

                                                    text
0      Showers continued throughout the week in the B...
1      Standard Oil Co and BP North America Inc said ...
2      Texas Commerce Bancshares Inc's Texas Commerce...
3      BankAmerica Corp is not under pressure to act ...
4      The U.S. Agriculture Department reported the f...
...                                                  ...
19038  The Japan/India-Pakistan-Gulf/Japan shipping c...
19039  The Soviet Union's industrial output is growin...
19040  Six black miners have been killed and two inju...
19041  The prospect of a dominant alliance of sociali...
19042  The American Stock Exchange said it has introd...

[19043 rows x 1 columns]

In [38]:
reuters_drop_na['text'][5667]

"Consolidated Rail Corp said it and CSX Corp's CSX Transportation Corp subsidiary have reduced rates on boxcar shipments of manufactured products moving between CSX points in the South and Conrail points in the Northeast and Midwest. Conrail said the prices, which were effective March one, are expected to meet or beat comparable truck transportation prices in virtually all target markets. It said the reduced prices also represent a simplification of the prvious tariff-based rate structure, which used price and milage scales to determine rates. The new prices are constructed from a single table of origin and destination Zip Codes."

In [33]:
reuters_drop_na_topics = pd.read_csv('processed/reuters_drop_na_topics.csv')

reuters_drop_na_topics

                                                    text
0      Showers continued throughout the week in the B...
1      The U.S. Agriculture Department reported the f...
2      Argentine grain board figures show crop regist...
3      Champion Products Inc said its board of direct...
4      Computer Terminal Systems Inc said it has comp...
...                                                  ...
10372  Chase Corp Ltd <CHCA.WE> said it will make an ...
10373  Tokyo's foreign exchange market is watching ne...
10374  The Japan/India-Pakistan-Gulf/Japan shipping c...
10375  The Soviet Union's industrial output is growin...
10376  Six black miners have been killed and two inju...

[10377 rows x 1 columns]

In [12]:
df_clean.shape

(10377, 1)

In [16]:
labels = df['topics'].tolist()

labels

[['cocoa'],
 ['grain', 'wheat', 'corn', 'barley', 'oat', 'sorghum'],
 ['veg-oil',
  'linseed',
  'lin-oil',
  'soy-oil',
  'sun-oil',
  'soybean',
  'oilseed',
  'corn',
  'sunseed',
  'grain',
  'sorghum',
  'wheat'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn', 'acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['wheat', 'grain'],
 ['copper'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['housing'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['coffee'],
 ['acq', 'ship'],
 ['acq'],
 ['sugar'],
 ['trade'],
 ['reserves'],
 ['ship'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['grain', 'corn'],
 ['money-supply'],
 ['ship'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['veg-oil', 'soybean', 'oilseed', 'meal-feed', 'soy-meal'],
 ['earn'],
 ['earn'],
 ['coffee'],
 ['money-supply'],
 ['money-supply'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['grain', 'wheat', 'corn', 'oat', 'rye', 'sorghum', 'soybean', 'oilseed'],
 ['earn'],
 ['money-supply'],
 ['cotton'],
 ['sugar'],
 ['grain', 'ship'],
 ['earn'],
 ['money-supply'],
 ['acq'],
 ['money-supply'],
 ['earn'],
 ['carcass', 'livestock'],
 ['earn'],
 ['grain'],
 ['acq'],
 ['earn'],
 ['crude'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['grain'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['crude'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['nat-gas'],
 ['cpi', 'gnp'],
 ['grain', 'wheat'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['crude'],
 ['grain', 'corn'],
 ['crude'],
 ['earn'],
 ['grain', 'corn', 'oat'],
 ['money-supply'],
 ['acq'],
 ['veg-oil', 'oilseed', 'meal-feed', 'soybean', 'soy-oil', 'soy-meal'],
 ['earn'],
 ['earn'],
 ['money-supply'],
 ['cpi', 'gnp'],
 ['earn'],
 ['crude'],
 ['earn'],
 ['cpi'],
 ['earn'],
 ['money-supply'],
 ['money-fx', 'interest'],
 ['interest'],
 ['gnp', 'bop'],
 ['grain', 'rice'],
 ['soybean', 'red-bean', 'oilseed'],
 ['coffee'],
 ['interest'],
 ['grain',
  'wheat',
  'rice',
  'veg-oil',
  'soybean',
  'sugar',
  'rubber',
  'copra-cake',
  'corn',
  'palm-oil',
  'palmkernel',
  'coffee',
  'tea',
  'plywood',
  'soy-meal',
  'cotton'],
 ['crude'],
 ['crude'],
 ['grain', 'wheat'],
 ['crude'],
 ['crude'],
 ['money-fx'],
 ['crude'],
 ['coffee'],
 ['grain', 'wheat'],
 ['grain', 'wheat'],
 ['money-fx'],
 ['sugar'],
 ['acq'],
 ['meal-feed', 'copra-cake'],
 ['trade'],
 ['alum'],
 ['crude'],
 ['veg-oil', 'palm-oil'],
 ['tea', 'cocoa', 'coffee'],
 ['earn'],
 ['ship'],
 ['reserves'],
 ['coffee'],
 ['sugar'],
 ['money-fx', 'interest'],
 ['oilseed', 'soybean'],
 ['earn'],
 ['acq'],
 ['oilseed', 'soybean', 'meal-feed', 'soy-meal'],
 ['acq'],
 ['money-fx', 'interest'],
 ['gold', 'platinum', 'strategic-metal'],
 ['meal-feed', 'tapioca'],
 ['tin'],
 ['trade', 'bop'],
 ['oilseed',
  'sunseed',
  'soybean',
  'rapeseed',
  'veg-oil',
  'soy-oil',
  'palm-oil',
  'groundnut-oil'],
 ['gold'],
 ['acq'],
 ['earn'],
 ['veg-oil', 'rape-oil', 'palm-oil'],
 ['interest'],
 ['reserves'],
 ['meal-feed',
  'soy-meal',
  'tapioca',
  'grain',
  'corn',
  'cornglutenfeed',
  'citruspulp',
  'oilseed',
  'rapeseed',
  'rape-meal'],
 ['money-supply'],
 ['acq'],
 ['veg-oil', 'palm-oil'],
 ['acq'],
 ['money-fx', 'interest'],
 ['trade'],
 ['money-fx', 'interest'],
 ['trade'],
 ['sugar'],
 ['earn'],
 ['strategic-metal'],
 ['crude'],
 ['crude'],
 ['crude'],
 ['trade'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['crude', 'ship'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['cotton'],
 ['acq'],
 ['alum'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['grain', 'wheat', 'corn', 'barley'],
 ['earn'],
 ['acq'],
 ['coffee'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['money-fx', 'interest'],
 ['reserves'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['grain', 'wheat', 'wool', 'dlr'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['livestock', 'l-cattle'],
 ['retail'],
 ['acq'],
 ['gold', 'acq', 'platinum'],
 ['earn'],
 ['ipi'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn', 'acq'],
 ['acq'],
 ['money-fx', 'interest'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['oilseed'],
 ['gold', 'silver'],
 ['crude'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['grain', 'corn', 'wheat', 'barley'],
 ['crude'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['grain', 'corn'],
 ['earn'],
 ['ship'],
 ['earn'],
 ['money-fx', 'interest'],
 ['earn'],
 ['iron-steel'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['crude'],
 ['nat-gas'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['coffee'],
 ['ship'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['sugar'],
 ['rubber'],
 ['earn'],
 ['earn'],
 ['tin'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['gold'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['crude'],
 ['acq'],
 ['earn'],
 ['crude', 'nat-gas'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['trade'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn', 'acq'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['grain', 'wheat'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['coffee'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['crude'],
 ['copper'],
 ['acq'],
 ['livestock', 'hog'],
 ['copper'],
 ['earn'],
 ['copper'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['propane', 'heat', 'gas'],
 ['veg-oil', 'soy-oil', 'oilseed', 'soybean'],
 ['heat'],
 ['crude'],
 ['acq'],
 ['earn'],
 ['money-supply'],
 ['acq'],
 ['coffee'],
 ['gnp', 'trade'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['grain', 'oat', 'corn', 'oilseed', 'soybean'],
 ['grain', 'wheat'],
 ['ship'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['jobs'],
 ['earn'],
 ['lei'],
 ['money-fx', 'yen', 'dlr'],
 ['crude'],
 ['grain', 'wheat'],
 ['coffee'],
 ['bop'],
 ['acq'],
 ['earn'],
 ['rubber'],
 ['veg-oil', 'palm-oil'],
 ['earn'],
 ['jobs'],
 ['bop'],
 ['trade'],
 ['jobs'],
 ['reserves'],
 ['bop'],
 ['earn'],
 ['money-fx'],
 ['acq'],
 ['tin'],
 ['money-fx', 'interest'],
 ['money-fx', 'saudriyal'],
 ['crude'],
 ['earn'],
 ['earn', 'alum'],
 ['earn'],
 ['trade'],
 ['trade'],
 ['interest', 'money-fx'],
 ['cpi'],
 ['crude'],
 ['acq'],
 ['reserves'],
 ['earn', 'alum'],
 ['acq'],
 ['money-supply'],
 ['acq'],
 ['interest', 'money-fx'],
 ['money-fx', 'interest'],
 ['veg-oil', 'palm-oil'],
 ['crude'],
 ['crude'],
 ['money-fx', 'interest'],
 ['jobs'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['ship'],
 ['earn'],
 ['lei'],
 ['earn'],
 ['coffee'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn', 'crude'],
 ['trade'],
 ['earn'],
 ['earn'],
 ['money-fx', 'interest'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['money-fx', 'interest'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['trade'],
 ['lei'],
 ['earn'],
 ['coffee', 'crude'],
 ['acq'],
 ['coffee'],
 ['acq'],
 ['earn'],
 ['housing'],
 ['acq'],
 ['jobs'],
 ['earn'],
 ['earn'],
 ['ship'],
 ['grain', 'wheat'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['grain', 'wheat', 'barley'],
 ['gnp'],
 ['grain', 'wheat'],
 ['earn'],
 ['earn'],
 ['gold'],
 ['acq'],
 ['acq'],
 ['zinc'],
 ['interest'],
 ['ipi'],
 ['earn'],
 ['gold'],
 ['earn'],
 ['coffee'],
 ['earn'],
 ['money-fx'],
 ['earn'],
 ['grain', 'wheat'],
 ['earn'],
 ['acq'],
 ['bop'],
 ['earn'],
 ['gnp'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['veg-oil', 'livestock', 'carcass'],
 ['earn'],
 ['money-fx', 'interest'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['interest'],
 ['earn'],
 ['grain', 'corn', 'sorghum'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['cpi'],
 ['copper'],
 ['oilseed', 'rapeseed'],
 ['earn'],
 ['acq'],
 ['money-fx', 'interest'],
 ['iron-steel'],
 ['earn'],
 ['ipi'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['reserves'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['copper'],
 ['grain', 'wheat'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['trade'],
 ['earn'],
 ['earn'],
 ['trade'],
 ['acq'],
 ['earn'],
 ['coffee'],
 ['earn'],
 ['acq'],
 ['trade'],
 ['veg-oil'],
 ['coffee'],
 ['acq'],
 ['meal-feed', 'soy-meal', 'grain', 'corn'],
 ['sugar'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['trade'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['coffee'],
 ['earn'],
 ['earn'],
 ['grain', 'wheat', 'ship'],
 ['earn'],
 ['earn'],
 ['alum'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['gnp'],
 ['grain', 'corn'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['grain', 'wheat'],
 ['earn'],
 ['grain'],
 ['alum'],
 ['earn'],
 ['acq'],
 ['crude'],
 ['money-supply'],
 ['earn'],
 ['coffee'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['alum'],
 ['crude'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['crude'],
 ['earn'],
 ['earn'],
 ['trade'],
 ['orange'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['trade'],
 ['earn'],
 ['earn'],
 ['orange'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['grain', 'corn', 'sorghum'],
 ['livestock', 'carcass'],
 ['earn'],
 ['grain', 'wheat'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['wheat', 'corn'],
 ['crude'],
 ['grain', 'wheat'],
 ['earn'],
 ['livestock', 'carcass'],
 ['oilseed', 'soybean'],
 ['grain', 'corn'],
 ['grain', 'wheat'],
 ['livestock', 'carcass'],
 ['grain', 'corn'],
 ['earn'],
 ['grain', 'cotton', 'wheat', 'oat', 'oilseed', 'soybean'],
 ['grain'],
 ['carcass'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['money-fx', 'interest'],
 ['acq'],
 ['interest'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['sugar'],
 ['rubber'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['money-fx'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['trade'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['pet-chem'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['trade'],
 ['acq'],
 ['earn'],
 ['money-fx', 'interest'],
 ['acq'],
 ['acq'],
 ['sugar'],
 ['gas'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['money-fx', 'dlr'],
 ['rubber'],
 ['earn'],
 ['sugar'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['cpi'],
 ['interest', 'money-fx'],
 ['earn'],
 ['earn'],
 ['crude', 'ship'],
 ['livestock', 'carcass', 'grain'],
 ['money-fx', 'interest'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['grain', 'wheat'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['coffee'],
 ['acq'],
 ['grain', 'corn', 'sorghum', 'oilseed', 'sunseed', 'soybean'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['trade'],
 ['grain', 'wheat', 'cotton', 'rice'],
 ['sugar'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['gold', 'copper'],
 ['earn'],
 ['earn'],
 ['bop', 'trade', 'gnp'],
 ['crude'],
 ['nat-gas'],
 ['earn'],
 ['acq'],
 ['grain'],
 ['acq'],
 ['acq'],
 ['grain'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['grain', 'wheat'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['grain', 'barley', 'corn'],
 ['earn'],
 ['earn'],
 ['trade'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['gas', 'fuel'],
 ['nat-gas', 'crude'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['grain', 'wheat'],
 ['trade'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['trade'],
 ['cpi'],
 ['earn'],
 ['acq'],
 ['crude'],
 ['earn'],
 ['earn'],
 ['crude'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['crude', 'nat-gas'],
 ['crude'],
 ['earn'],
 ['coffee'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['ship'],
 ['interest', 'money-fx'],
 ['earn'],
 ['acq'],
 ['grain'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['orange'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['livestock', 'carcass', 'trade'],
 ['reserves'],
 ['grain', 'corn', 'wheat'],
 ['earn'],
 ['sugar'],
 ['acq'],
 ['acq'],
 ['acq'],
 ['grain', 'wheat', 'oilseed', 'soybean'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['acq'],
 ['trade'],
 ['money-fx', 'trade'],
 ['earn'],
 ['sugar'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['alum'],
 ['acq'],
 ['acq'],
 ['earn'],
 ['trade'],
 ['coffee'],
 ['grain', 'corn', 'sorghum'],
 ['grain'],
 ['earn'],
 ['acq'],
 ['veg-oil'],
 ['earn'],
 ['earn'],
 ['crude', 'gas', 'fuel'],
 ['gnp'],
 ['acq', 'earn'],
 ['earn'],
 ['acq'],
 ['trade'],
 ['trade'],
 ['earn'],
 ['earn'],
 ['crude'],
 ['earn'],
 ['crude', 'gas'],
 ['coffee'],
 ['grain', 'cotton', 'rice', 'oilseed', 'soybean'],
 ['reserves'],
 ['acq'],
 ['coffee'],
 ['bop', 'trade'],
 ['gold'],
 ['money-supply'],
 ['grain', 'wheat', 'ship'],
 ['ship'],
 ['ship', 'crude'],
 ['grain', 'wheat'],
 ['crude'],
 ['coffee'],
 ['money-supply'],
 ['reserves'],
 ['grain', 'rice'],
 ['money-fx'],
 ['earn'],
 ['gold'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['money-fx', 'dlr', 'yen'],
 ['tin'],
 ['money-fx', 'interest'],
 ['trade'],
 ['money-supply'],
 ['iron-steel'],
 ['reserves', 'trade'],
 ['silver', 'gold'],
 ['money-fx', 'interest'],
 ['sugar'],
 ['crude'],
 ['money-fx'],
 ['trade'],
 ['grain', 'corn'],
 ['gnp'],
 ['coffee'],
 ['trade'],
 ['trade', 'bop'],
 ['wpi'],
 ['oilseed'],
 ['money-fx', 'interest'],
 ['grain',
  'potato',
  'wheat',
  'barley',
  'meal-feed',
  'soy-meal',
  'hog',
  'carcass',
  'livestock'],
 ['interest'],
 ['sugar'],
 ['money-fx', 'interest'],
 ['crude', 'ship'],
 ['money-fx', 'interest'],
 ['money-fx'],
 ['crude'],
 ['acq'],
 ['interest'],
 ['acq'],
 ['jobs'],
 ['earn'],
 ['grain', 'wheat'],
 ['earn'],
 ['copper'],
 ['crude', 'nat-gas'],
 ['grain', 'wheat'],
 ['acq'],
 ['ship'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['money-fx', 'interest'],
 ['acq'],
 ['money-fx'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['grain', 'wheat', 'barley', 'corn'],
 ['crude'],
 ['earn'],
 ['earn'],
 ['earn'],
 ['acq'],
 ['earn'],
 ['earn'],
 ['earn', 'crude'],
 ['interest'],
 ['earn'],
 ['gold'],
 ['grain', 'wheat', 'copper'],
 ['earn'],
 ...]

In [16]:
import ast

clean_data = []

for item in labels:
    # Safely convert the string "['acq, yen']" into a real Python list ['acq, yen']
    evaluated_list = ast.literal_eval(item)
    
    for item in evaluated_list:
        clean_data.append(item)

print(clean_data)
# Output: ['cocoa', 'acq', 'yen', 'sugar', 'coffee']

['cocoa', 'grain', 'wheat', 'corn', 'barley', 'oat', 'sorghum', 'veg-oil', 'linseed', 'lin-oil', 'soy-oil', 'sun-oil', 'soybean', 'oilseed', 'corn', 'sunseed', 'grain', 'sorghum', 'wheat', 'earn', 'acq', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'wheat', 'grain', 'copper', 'earn', 'earn', 'earn', 'housing', 'earn', 'earn', 'earn', 'earn', 'earn', 'coffee', 'acq', 'ship', 'acq', 'sugar', 'trade', 'reserves', 'ship', 'earn', 'earn', 'earn', 'grain', 'corn', 'money-supply', 'ship', 'earn', 'earn', 'earn', 'acq', 'veg-oil', 'soybean', 'oilseed', 'meal-feed', 'soy-meal', 'earn', 'earn', 'coffee', 'money-supply', 'money-supply', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'grain', 'wheat', 'corn', 'oat', 'rye', 'sorghum', 'soybean', 'oilseed', 'earn', 'money-supply', 'cotton', 'sugar', 'grain', 'ship', 'earn', 'money-supply', 'acq', 'money-supply', 'earn', 'carcass', 'livestock', 'earn', 'grain', 'acq', 'earn', 'crude', 'acq', 'earn', 'acq', 'acq', 'grain', 'earn', 'earn', 'earn', 'earn', 'earn', 'crude', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'acq', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'nat-gas', 'cpi', 'gnp', 'grain', 'wheat', 'earn', 'acq', 'acq', 'earn', 'crude', 'grain', 'corn', 'crude', 'earn', 'grain', 'corn', 'oat', 'money-supply', 'acq', 'veg-oil', 'oilseed', 'meal-feed', 'soybean', 'soy-oil', 'soy-meal', 'earn', 'earn', 'money-supply', 'cpi', 'gnp', 'earn', 'crude', 'earn', 'cpi', 'earn', 'money-supply', 'money-fx', 'interest', 'interest', 'gnp', 'bop', 'grain', 'rice', 'soybean', 'red-bean', 'oilseed', 'coffee', 'interest', 'grain', 'wheat', 'rice', 'veg-oil', 'soybean', 'sugar', 'rubber', 'copra-cake', 'corn', 'palm-oil', 'palmkernel', 'coffee', 'tea', 'plywood', 'soy-meal', 'cotton', 'crude', 'crude', 'grain', 'wheat', 'crude', 'crude', 'money-fx', 'crude', 'coffee', 'grain', 'wheat', 'grain', 'wheat', 'money-fx', 'sugar', 'acq', 'meal-feed', 'copra-cake', 'trade', 'alum', 'crude', 'veg-oil', 'palm-oil', 'tea', 'cocoa', 'coffee', 'earn', 'ship', 'reserves', 'coffee', 'sugar', 'money-fx', 'interest', 'oilseed', 'soybean', 'earn', 'acq', 'oilseed', 'soybean', 'meal-feed', 'soy-meal', 'acq', 'money-fx', 'interest', 'gold', 'platinum', 'strategic-metal', 'meal-feed', 'tapioca', 'tin', 'trade', 'bop', 'oilseed', 'sunseed', 'soybean', 'rapeseed', 'veg-oil', 'soy-oil', 'palm-oil', 'groundnut-oil', 'gold', 'acq', 'earn', 'veg-oil', 'rape-oil', 'palm-oil', 'interest', 'reserves', 'meal-feed', 'soy-meal', 'tapioca', 'grain', 'corn', 'cornglutenfeed', 'citruspulp', 'oilseed', 'rapeseed', 'rape-meal', 'money-supply', 'acq', 'veg-oil', 'palm-oil', 'acq', 'money-fx', 'interest', 'trade', 'money-fx', 'interest', 'trade', 'sugar', 'earn', 'strategic-metal', 'crude', 'crude', 'crude', 'trade', 'earn', 'acq', 'acq', 'acq', 'crude', 'ship', 'acq', 'acq', 'acq', 'cotton', 'acq', 'alum', 'earn', 'acq', 'earn', 'acq', 'earn', 'acq', 'earn', 'acq', 'grain', 'wheat', 'corn', 'barley', 'earn', 'acq', 'coffee', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'money-fx', 'interest', 'reserves', 'earn', 'earn', 'earn', 'acq', 'grain', 'wheat', 'wool', 'dlr', 'earn', 'acq', 'earn', 'earn', 'acq', 'acq', 'livestock', 'l-cattle', 'retail', 'acq', 'gold', 'acq', 'platinum', 'earn', 'ipi', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'acq', 'acq', 'money-fx', 'interest', 'acq', 'earn', 'earn', 'earn', 'oilseed', 'gold', 'silver', 'crude', 'earn', 'earn', 'acq', 'acq', 'acq', 'grain', 'corn', 'wheat', 'barley', 'crude', 'acq', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'grain', 'corn', 'earn', 'ship', 'earn', 'money-fx', 'interest', 'earn', 'iron-steel', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'crude', 'nat-gas', 'acq', 'earn', 'acq', 'earn', 'acq', 'acq', 'earn', 'acq', 'earn', 'earn', 'earn', 'acq', 'acq', 'earn', 'coffee', 'ship', 'acq', 'earn', 'acq', 'sugar', 'rubber', 'earn', 'earn', 'tin', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'gold', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'crude', 'acq', 'earn', 'crude', 'nat-gas', 'acq', 'acq', 'earn', 'trade', 'earn', 'acq', 'acq', 'earn', 'earn', 'acq', 'earn', 'acq', 'acq', 'earn', 'acq', 'acq', 'earn', 'acq', 'grain', 'wheat', 'earn', 'acq', 'acq', 'coffee', 'earn', 'acq', 'earn', 'acq', 'acq', 'acq', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'crude', 'copper', 'acq', 'livestock', 'hog', 'copper', 'earn', 'copper', 'earn', 'earn', 'acq', 'earn', 'propane', 'heat', 'gas', 'veg-oil', 'soy-oil', 'oilseed', 'soybean', 'heat', 'crude', 'acq', 'earn', 'money-supply', 'acq', 'coffee', 'gnp', 'trade', 'acq', 'earn', 'earn', 'acq', 'acq', 'acq', 'earn', 'acq', 'grain', 'oat', 'corn', 'oilseed', 'soybean', 'grain', 'wheat', 'ship', 'earn', 'earn', 'earn', 'earn', 'jobs', 'earn', 'lei', 'money-fx', 'yen', 'dlr', 'crude', 'grain', 'wheat', 'coffee', 'bop', 'acq', 'earn', 'rubber', 'veg-oil', 'palm-oil', 'earn', 'jobs', 'bop', 'trade', 'jobs', 'reserves', 'bop', 'earn', 'money-fx', 'acq', 'tin', 'money-fx', 'interest', 'money-fx', 'saudriyal', 'crude', 'earn', 'earn', 'alum', 'earn', 'trade', 'trade', 'interest', 'money-fx', 'cpi', 'crude', 'acq', 'reserves', 'earn', 'alum', 'acq', 'money-supply', 'acq', 'interest', 'money-fx', 'money-fx', 'interest', 'veg-oil', 'palm-oil', 'crude', 'crude', 'money-fx', 'interest', 'jobs', 'acq', 'acq', 'earn', 'ship', 'earn', 'lei', 'earn', 'coffee', 'acq', 'acq', 'earn', 'earn', 'earn', 'earn', 'crude', 'trade', 'earn', 'earn', 'money-fx', 'interest', 'acq', 'earn', 'earn', 'money-fx', 'interest', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'trade', 'lei', 'earn', 'coffee', 'crude', 'acq', 'coffee', 'acq', 'earn', 'housing', 'acq', 'jobs', 'earn', 'earn', 'ship', 'grain', 'wheat', 'earn', 'earn', 'earn', 'earn', 'grain', 'wheat', 'barley', 'gnp', 'grain', 'wheat', 'earn', 'earn', 'gold', 'acq', 'acq', 'zinc', 'interest', 'ipi', 'earn', 'gold', 'earn', 'coffee', 'earn', 'money-fx', 'earn', 'grain', 'wheat', 'earn', 'acq', 'bop', 'earn', 'gnp', 'acq', 'acq', 'earn', 'earn', 'veg-oil', 'livestock', 'carcass', 'earn', 'money-fx', 'interest', 'earn', 'acq', 'earn', 'acq', 'earn', 'interest', 'earn', 'grain', 'corn', 'sorghum', 'earn', 'earn', 'earn', 'earn', 'cpi', 'copper', 'oilseed', 'rapeseed', 'earn', 'acq', 'money-fx', 'interest', 'iron-steel', 'earn', 'ipi', 'acq', 'earn', 'earn', 'earn', 'earn', 'reserves', 'earn', 'earn', 'earn', 'earn', 'earn', 'copper', 'grain', 'wheat', 'earn', 'earn', 'earn', 'earn', 'trade', 'earn', 'earn', 'trade', 'acq', 'earn', 'coffee', 'earn', 'acq', 'trade', 'veg-oil', 'coffee', 'acq', 'meal-feed', 'soy-meal', 'grain', 'corn', 'sugar', 'acq', 'acq', 'earn', 'trade', 'acq', 'earn', 'earn', 'acq', 'earn', 'acq', 'earn', 'earn', 'coffee', 'earn', 'earn', 'grain', 'wheat', 'ship', 'earn', 'earn', 'alum', 'earn', 'earn', 'earn', 'earn', 'gnp', 'grain', 'corn', 'acq', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'acq', 'earn', 'grain', 'wheat', 'earn', 'grain', 'alum', 'earn', 'acq', 'crude', 'money-supply', 'earn', 'coffee', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'alum', 'crude', 'earn', 'acq', 'earn', 'earn', 'crude', 'earn', 'earn', 'trade', 'orange', 'earn', 'acq', 'earn', 'trade', 'earn', 'earn', 'orange', 'earn', 'earn', 'earn', 'earn', 'grain', 'corn', 'sorghum', 'livestock', 'carcass', 'earn', 'grain', 'wheat', 'earn', 'earn', 'earn', 'earn', 'earn', 'wheat', 'corn', 'crude', 'grain', 'wheat', 'earn', 'livestock', 'carcass', 'oilseed', 'soybean', 'grain', 'corn', 'grain', 'wheat', 'livestock', 'carcass', 'grain', 'corn', 'earn', 'grain', 'cotton', 'wheat', 'oat', 'oilseed', 'soybean', 'grain', 'carcass', 'acq', 'acq', 'earn', 'earn', 'money-fx', 'interest', 'acq', 'interest', 'earn', 'acq', 'earn', 'earn', 'earn', 'sugar', 'rubber', 'earn', 'earn', 'earn', 'earn', 'earn', 'money-fx', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'trade', 'acq', 'earn', 'earn', 'earn', 'pet-chem', 'earn', 'earn', 'acq', 'earn', 'trade', 'acq', 'earn', 'money-fx', 'interest', 'acq', 'acq', 'sugar', 'gas', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'money-fx', 'dlr', 'rubber', 'earn', 'sugar', 'earn', 'earn', 'earn', 'earn', 'cpi', 'interest', 'money-fx', 'earn', 'earn', 'crude', 'ship', 'livestock', 'carcass', 'grain', 'money-fx', 'interest', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'grain', 'wheat', 'earn', 'earn', 'earn', 'acq', 'coffee', 'acq', 'grain', 'corn', 'sorghum', 'oilseed', 'sunseed', 'soybean', 'acq', 'earn', 'earn', 'trade', 'grain', 'wheat', 'cotton', 'rice', 'sugar', 'acq', 'earn', 'acq', 'gold', 'copper', 'earn', 'earn', 'bop', 'trade', 'gnp', 'crude', 'nat-gas', 'earn', 'acq', 'grain', 'acq', 'acq', 'grain', 'earn', 'acq', 'earn', 'earn', 'grain', 'wheat', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'grain', 'barley', 'corn', 'earn', 'earn', 'trade', 'earn', 'earn', 'acq', 'gas', 'fuel', 'nat-gas', 'crude', 'acq', 'acq', 'acq', 'acq', 'grain', 'wheat', 'trade', 'acq', 'earn', 'acq', 'acq', 'trade', 'cpi', 'earn', 'acq', 'crude', 'earn', 'earn', 'crude', 'acq', 'acq', 'earn', 'earn', 'earn', 'crude', 'nat-gas', 'crude', 'earn', 'coffee', 'earn', 'earn', 'earn', 'ship', 'interest', 'money-fx', 'earn', 'acq', 'grain', 'earn', 'earn', 'acq', 'acq', 'acq', 'acq', 'earn', 'earn', 'earn', 'earn', 'acq', 'orange', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'livestock', 'carcass', 'trade', 'reserves', 'grain', 'corn', 'wheat', 'earn', 'sugar', 'acq', 'acq', 'acq', 'grain', 'wheat', 'oilseed', 'soybean', 'earn', 'earn', 'acq', 'acq', 'earn', 'acq', 'trade', 'money-fx', 'trade', 'earn', 'sugar', 'earn', 'earn', 'earn', 'alum', 'acq', 'acq', 'earn', 'trade', 'coffee', 'grain', 'corn', 'sorghum', 'grain', 'earn', 'acq', 'veg-oil', 'earn', 'earn', 'crude', 'gas', 'fuel', 'gnp', 'acq', 'earn', 'earn', 'acq', 'trade', 'trade', 'earn', 'earn', 'crude', 'earn', 'crude', 'gas', 'coffee', 'grain', 'cotton', 'rice', 'oilseed', 'soybean', 'reserves', 'acq', 'coffee', 'bop', 'trade', 'gold', 'money-supply', 'grain', 'wheat', 'ship', 'ship', 'ship', 'crude', 'grain', 'wheat', 'crude', 'coffee', 'money-supply', 'reserves', 'grain', 'rice', 'money-fx', 'earn', 'gold', 'earn', 'acq', 'earn', 'money-fx', 'dlr', 'yen', 'tin', 'money-fx', 'interest', 'trade', 'money-supply', 'iron-steel', 'reserves', 'trade', 'silver', 'gold', 'money-fx', 'interest', 'sugar', 'crude', 'money-fx', 'trade', 'grain', 'corn', 'gnp', 'coffee', 'trade', 'trade', 'bop', 'wpi', 'oilseed', 'money-fx', 'interest', 'grain', 'potato', 'wheat', 'barley', 'meal-feed', 'soy-meal', 'hog', 'carcass', 'livestock', 'interest', 'sugar', 'money-fx', 'interest', 'crude', 'ship', 'money-fx', 'interest', 'money-fx', 'crude', 'acq', 'interest', 'acq', 'jobs', 'earn', 'grain', 'wheat', 'earn', 'copper', 'crude', 'nat-gas', 'grain', 'wheat', 'acq', 'ship', 'acq', 'earn', 'earn', 'money-fx', 'interest', 'acq', 'money-fx', 'earn', 'acq', 'earn', 'earn', 'earn', 'acq', 'earn', 'grain', 'wheat', 'barley', 'corn', 'crude', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'crude', 'interest', 'earn', 'gold', 'grain', 'wheat', 'copper', 'earn', 'acq', 'oilseed', 'soybean', 'earn', 'earn', 'grain', 'wheat', 'acq', 'earn', 'earn', 'acq', 'acq', 'earn', 'earn', 'reserves', 'earn', 'acq', 'coffee', 'earn', 'acq', 'crude', 'acq', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'interest', 'acq', 'earn', 'earn', 'livestock', 'grain', 'barley', 'wheat', 'corn', 'oilseed', 'rapeseed', 'earn', 'crude', 'earn', 'copper', 'lead', 'zinc', 'strategic-metal', 'crude', 'ship', 'earn', 'money-fx', 'dlr', 'yen', 'grain', 'wheat', 'barley', 'acq', 'earn', 'earn', 'sugar', 'acq', 'earn', 'gnp', 'jobs', 'earn', 'acq', 'earn', 'earn', 'sugar', 'earn', 'earn', 'earn', 'grain', 'wheat', 'barley', 'corn', 'acq', 'earn', 'grain', 'wheat', 'acq', 'acq', 'livestock', 'hog', 'carcass', 'earn', 'interest', 'earn', 'crude', 'grain', 'barley', 'earn', 'earn', 'acq', 'earn', 'sugar', 'acq', 'sugar', 'acq', 'earn', 'acq', 'earn', 'earn', 'acq', 'earn', 'earn', 'grain', 'corn', 'earn', 'earn', 'acq', 'retail', 'earn', 'acq', 'earn', 'earn', 'earn', 'gnp', 'trade', 'earn', 'acq', 'money-fx', 'yen', 'acq', 'acq', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'ship', 'earn', 'earn', 'earn', 'acq', 'acq', 'acq', 'ship', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'trade', 'money-fx', 'earn', 'money-fx', 'dlr', 'yen', 'earn', 'trade', 'sugar', 'cotton', 'groundnut', 'oilseed', 'acq', 'earn', 'grain', 'wheat', 'earn', 'pet-chem', 'acq', 'acq', 'acq', 'earn', 'earn', 'grain', 'wheat', 'corn', 'soybean', 'oilseed', 'crude', 'earn', 'earn', 'livestock', 'l-cattle', 'carcass', 'sugar', 'orange', 'earn', 'earn', 'nat-gas', 'earn', 'earn', 'earn', 'earn', 'money-fx', 'can', 'earn', 'acq', 'gold', 'trade', 'acq', 'veg-oil', 'groundnut', 'earn', 'grain', 'wheat', 'earn', 'earn', 'earn', 'acq', 'earn', 'grain', 'corn', 'earn', 'earn', 'acq', 'livestock', 'carcass', 'crude', 'money-fx', 'dlr', 'grain', 'corn', 'oilseed', 'soybean', 'veg-oil', 'soy-oil', 'meal-feed', 'soy-meal', 'cotton', 'earn', 'earn', 'acq', 'coffee', 'money-supply', 'acq', 'earn', 'acq', 'acq', 'acq', 'earn', 'earn', 'nat-gas', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'livestock', 'carcass', 'earn', 'trade', 'acq', 'earn', 'acq', 'grain', 'wheat', 'trade', 'crude', 'nat-gas', 'acq', 'earn', 'crude', 'nat-gas', 'crude', 'earn', 'earn', 'acq', 'coffee', 'oilseed', 'soybean', 'trade', 'sugar', 'cocoa', 'crude', 'grain', 'wheat', 'acq', 'acq', 'cpi', 'crude', 'retail', 'acq', 'acq', 'trade', 'grain', 'wheat', 'acq', 'earn', 'acq', 'ship', 'acq', 'earn', 'acq', 'earn', 'earn', 'coffee', 'acq', 'acq', 'coffee', 'money-supply', 'cpi', 'fishmeal', 'meal-feed', 'earn', 'gold', 'earn', 'earn', 'earn', 'money-fx', 'earn', 'earn', 'earn', 'earn', 'acq', 'hog', 'livestock', 'acq', 'money-fx', 'interest', 'acq', 'acq', 'earn', 'earn', 'acq', 'earn', 'crude', 'earn', 'earn', 'earn', 'livestock', 'acq', 'money-fx', 'interest', 'earn', 'acq', 'coffee', 'earn', 'acq', 'earn', 'earn', 'grain', 'corn', 'jobs', 'ipi', 'gnp', 'income', 'trade', 'retail', 'earn', 'trade', 'money-fx', 'interest', 'earn', 'dlr', 'money-fx', 'ship', 'acq', 'acq', 'earn', 'acq', 'trade', 'acq', 'acq', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'earn', 'acq', 'earn', 'earn', 'ship', 'money-fx', 'interest', 'money-supply', 'reserves', 'earn', 'crude', 'earn', 'earn', 'earn', 'heat', 'interest', 'money-fx', 'acq', 'earn', 'earn', 'interest', 'gnp', 'earn', 'acq', 'earn', 'earn', 'earn', 'interest', 'grain', 'corn', 'acq', 'earn', 'acq', 'grain', 'wheat', 'corn', 'earn', 'money-supply', 'jobs', 'grain', 'wheat', 'earn', 'grain', 'corn', 'earn', 'earn', 'earn', 'earn', 'earn', 'earn', 'sugar', 'earn', 'gold', 'acq', 'copper', 'money-fx', 'crude', 'acq', 'acq', 'earn', 'earn', 'earn', 'crude', 'sugar', 'corn', 'grain', 'earn', 'earn', 'gold', 'platinum', 'palladium', 'nickel', 'copper', 'acq', 'gold', 'earn', 'earn', 'acq', 'earn', 'lumber', 'earn', 'acq', 'earn', 'acq', 'earn', 'earn', 'earn', 'earn', 'acq', 'acq', 'acq', 'acq', 'ship', 'earn', 'earn', 'earn', 'earn', 'ship', 'gas', 'acq', 'earn', 'earn', 'crude', 'earn', 'gnp', 'acq', 'grain', 'corn', 'earn', 'earn', 'livestock', 'ship', 'earn', 'grain', 'wheat', 'money-supply', 'trade', 'grain', 'wheat', 'earn', 'acq', 'money-supply', 'earn', 'earn', 'gold', 'platinum', 'palladium', 'copper', 'nickel', 'livestock', 'acq', 'earn', 'earn', 'earn', 'acq', 'acq', 'acq', 'acq', 'acq', 'earn', 'earn', 'grain', 'corn', 'cornglutenfeed', 'meal-feed', 'earn', 'earn', 'acq', 'earn', 'earn', 'earn', 'grain', 'corn', 'nat-gas', 'acq', 'interest', 'crude', 'acq', 'acq', 'earn', 'earn', 'earn', 'acq', 'strategic-metal', 'earn', 'strategic-metal', 'ship', 'acq', 'acq', 'grain', 'corn', 'acq', 'acq', 'acq', 'interest', 'acq', 'coffee', 'ship', 'acq', 'crude', 'fuel', 'jet', 'ship', 'ship', 'earn', 'earn', 'earn', 'earn', 'sugar', 'gnp', 'interest', 'money-fx', 'ship', 'crude', 'ship', 'crude', 'tapioca', 'meal-feed', 'cotton', 'sugar', 'veg-oil', 'grain', 'sugar', 'rubber', 'carcass', 'livestock', 'interest', 'iron-steel', 'gold', 'trade', 'ipi', 'money-fx', 'money-supply', 'ipi', 'money-fx', 'interest', 'crude', 'acq', 'money-fx', 'money-fx', 'interest', 'crude', 'interest', 'earn', 'acq', 'strategic-metal', 'acq', 'crude', 'nat-gas', 'instal-debt', 'crude', 'ship', 'trade', 'gnp', 'bop', 'dlr', 'interest', 'money-fx', 'dlr', 'acq', 'gnp', 'jobs', 'cpi', 'bop', 'dfl', 'acq', 'earn', 'ship', 'money-fx', 'gnp', 'coffee', 'meal-feed', 'acq', 'acq', 'coffee', 'acq', 'interest', 'money-fx', 'interest', 'ship', 'ship', 'crude', 'rubber', 'acq', 'acq', 'hog', 'livestock', 'earn', 'acq', 'trade', 'bop', 'money-fx', 'crude', 'gnp', 'dlr', 'money-fx', 'money-fx', 'interest', 'acq', 'acq', 'acq', 'money-supply', 'money-fx', 'dlr', 'dmk', 'earn', 'trade', 'earn', 'grain', 'oilseed', 'grain', 'meal-feed', 'carcass', 'soy-meal', 'livestock', 'acq', 'acq', 'acq', 'earn', 'interest', 'acq', 'acq', 'acq', 'acq', 'orange', 'acq', 'interest', 'zinc', 'housing', 'acq', 'orange', 'ship', 'interest', 'crude', 'earn', 'earn', 'pet-chem', 'acq', 'money-fx', 'interest', 'interest', 'interest', 'acq', 'interest', 'grain', 'wheat', 'barley', 'interest', 'meal-feed', 'fishmeal', 'money-fx', 'interest', 'grain', 'wheat', 'corn', 'acq', 'acq', 'crude', 'nat-gas', 'orange', 'acq', 'acq', 'acq', 'rubber', 'acq', 'earn', 'zinc', 'interest', 'money-fx', 'acq', 'acq', 'crude', 'nat-gas', 'acq', 'crude', 'nat-gas', 'acq', 'acq', 'heat', 'zinc', 'acq', 'coffee', 'crude', 'grain', 'corn', 'sugar', 'interest', 'earn', 'acq', 'trade', 'crude', 'acq', 'oilseed', 'rapeseed', 'zinc', 'nat-gas', 'lead', 'acq', 'ship', 'interest', 'money-fx', 'acq', 'cocoa', 'sugar', 'acq', 'acq', 'acq', 'acq', 'earn', 'earn', 'gnp', 'money-supply', 'bop', 'acq', 'acq', 'interest', 'earn', 'ship', 'earn', 'ship', 'acq', 'acq', 'acq', 'acq', 'money-fx', 'dlr', 'trade', 'acq', 'earn', 'earn', 'grain', 'wheat', 'earn', 'earn', 'acq', 'acq', 'hog', 'l-cattle', 'livestock', 'oilseed', 'soybean', 'grain', 'corn', 'wheat', 'interest', 'stg', 'ship', 'acq', 'acq', 'money-fx', 'interest', 'acq', 'acq', 'acq', 'crude', 'grain', 'corn', 'acq', 'cocoa', 'coffee', 'sugar', 'heat', 'acq', 'grain', 'wheat', 'orange', 'potato', 'carcass', 'livestock', 'hog', 'acq', 'gold', 'grain', 'wheat', 'grain', 'barley', 'gold', 'ship', 'grain', 'wheat', 'corn', 'crude', 'grain', 'wheat', 'grain', 'wheat', 'acq', 'grain', 'corn', 'trade', 'bop', 'money-fx', 'dlr', 'livestock', 'livestock', 'crude', 'earn', 'acq', 'ship', 'money-supply', 'ship', 'gnp', 'gnp', 'instal-debt', 'acq', 'grain', 'corn', 'wheat', 'rice', 'interest', 'crude', 'acq', 'interest', 'acq', 'acq', 'acq', 'earn', 'acq', 'earn', 'acq', 'grain', 'ship', 'acq', 'crude', 'grain', 'acq', 'acq', 'acq', 'acq', 'acq', 'grain', 'wheat', 'corn', 'earn', 'acq', 'gnp', 'cpi', 'money-fx', 'acq', 'acq', 'acq', 'acq', 'acq', 'earn', 'money-fx', 'dlr', 'yen', 'acq', 'acq', 'grain', 'corn', 'wheat', 'crude', 'money-fx', 'money-fx', 'rubber', 'ship', 'trade', 'money-fx', 'grain', 'wheat', 'rice', 'trade', 'interest', 'crude', 'oilseed', 'soybean', 'zinc', 'lead', 'copper', 'crude', 'earn', 'oilseed', 'soybean', 'acq', 'strategic-metal', 'money-fx', 'earn', 'earn', 'oilseed', 'soybean', 'earn', 'iron-steel', 'jobs', 'ship', 'earn', 'acq', 'earn', 'money-fx', 'money-fx', 'earn', 'bop', 'earn', 'acq', 'sugar', 'interest', 'money-fx', 'earn', 'strategic-metal', 'veg-oil', 'palm-oil', 'earn', 'crude', 'crude', 'sugar', 'trade', 'bop', 'money-fx', 'earn', 'jobs', 'money-supply', 'interest', 'money-fx', 'interest', 'lei', 'money-fx', 'yen', 'trade', 'money-fx', 'interest', 'money-fx', 'stg', 'c

In [26]:
nan_count = 0

for i in range(len(labels)):
    if labels[i] is np.nan:
        nan_count += 1

print("Number of NaN labels:", nan_count)

Number of NaN labels: 8666

In [27]:
import ast

In [17]:
dict_labels = dict()

for i in range(len(labels)):

    if(labels[i] is not np.nan):
        label = labels[i]

        for j in range(len(label)):
            if label[j] not in dict_labels:
                dict_labels[label[j]] = 1
            else:
                dict_labels[label[j]] += 1


print("Unique labels:", list(dict_labels.keys()))
print("Label counts:", list(dict_labels.values()))

Unique labels: ['cocoa', 'grain', 'wheat', 'corn', 'barley', 'oat', 'sorghum', 'veg-oil', 'linseed', 'lin-oil', 'soy-oil', 'sun-oil', 'soybean', 'oilseed', 'sunseed', 'earn', 'acq', 'copper', 'housing', 'coffee', 'ship', 'sugar', 'trade', 'reserves', 'money-supply', 'meal-feed', 'soy-meal', 'rye', 'cotton', 'carcass', 'livestock', 'crude', 'nat-gas', 'cpi', 'gnp', 'money-fx', 'interest', 'bop', 'rice', 'red-bean', 'rubber', 'copra-cake', 'palm-oil', 'palmkernel', 'tea', 'plywood', 'alum', 'gold', 'platinum', 'strategic-metal', 'tapioca', 'tin', 'rapeseed', 'groundnut-oil', 'rape-oil', 'cornglutenfeed', 'citruspulp', 'rape-meal', 'wool', 'dlr', 'l-cattle', 'retail', 'ipi', 'silver', 'iron-steel', 'hog', 'propane', 'heat', 'gas', 'jobs', 'lei', 'yen', 'saudriyal', 'zinc', 'orange', 'pet-chem', 'fuel', 'wpi', 'potato', 'lead', 'groundnut', 'can', 'fishmeal', 'income', 'palladium', 'nickel', 'lumber', 'jet', 'instal-debt', 'dfl', 'dmk', 'stg', 'coconut-oil', 'corn-oil', 'inventories', 'cpu', 'peseta', 'austdlr', 'cotton-oil', 'naphtha', 'nzdlr', 'rand', 'pork-belly', 'ringgit', 'coconut', 'castorseed', 'castor-oil', 'lit', 'rupiah', 'skr', 'nkr', 'dkr', 'sun-meal', 'lin-meal', 'cottonseed', 'f-cattle', 'bfr', 'hk', 'sfr']
Label counts: [68, 574, 287, 224, 48, 13, 34, 136, 2, 2, 25, 8, 111, 182, 17, 3776, 2210, 77, 18, 143, 295, 175, 515, 73, 126, 50, 26, 2, 62, 75, 112, 566, 126, 101, 153, 684, 424, 101, 67, 1, 49, 3, 42, 3, 15, 4, 58, 133, 11, 32, 4, 33, 35, 2, 8, 2, 1, 1, 2, 168, 9, 23, 57, 36, 65, 26, 6, 25, 55, 68, 13, 58, 3, 43, 25, 41, 28, 29, 6, 35, 10, 3, 2, 12, 3, 11, 17, 8, 5, 3, 14, 17, 7, 1, 6, 2, 1, 4, 3, 7, 4, 3, 3, 1, 6, 1, 2, 3, 1, 1, 2, 1, 2, 1, 1, 3, 1, 1, 3]

In [23]:
np.average(list(dict_labels.values()))

np.float64(110.26890756302521)

In [24]:
print(dict_labels)

{'cocoa': 68, 'grain': 574, 'wheat': 287, 'corn': 224, 'barley': 48, 'oat': 13, 'sorghum': 34, 'veg-oil': 136, 'linseed': 2, 'lin-oil': 2, 'soy-oil': 25, 'sun-oil': 8, 'soybean': 111, 'oilseed': 182, 'sunseed': 17, 'earn': 3776, 'acq': 2210, 'copper': 77, 'housing': 18, 'coffee': 143, 'ship': 295, 'sugar': 175, 'trade': 515, 'reserves': 73, 'money-supply': 126, 'meal-feed': 50, 'soy-meal': 26, 'rye': 2, 'cotton': 62, 'carcass': 75, 'livestock': 112, 'crude': 566, 'nat-gas': 126, 'cpi': 101, 'gnp': 153, 'money-fx': 684, 'interest': 424, 'bop': 101, 'rice': 67, 'red-bean': 1, 'rubber': 49, 'copra-cake': 3, 'palm-oil': 42, 'palmkernel': 3, 'tea': 15, 'plywood': 4, 'alum': 58, 'gold': 133, 'platinum': 11, 'strategic-metal': 32, 'tapioca': 4, 'tin': 33, 'rapeseed': 35, 'groundnut-oil': 2, 'rape-oil': 8, 'cornglutenfeed': 2, 'citruspulp': 1, 'rape-meal': 1, 'wool': 2, 'dlr': 168, 'l-cattle': 9, 'retail': 23, 'ipi': 57, 'silver': 36, 'iron-steel': 65, 'hog': 26, 'propane': 6, 'heat': 25, 'gas': 55, 'jobs': 68, 'lei': 13, 'yen': 58, 'saudriyal': 3, 'zinc': 43, 'orange': 25, 'pet-chem': 41, 'fuel': 28, 'wpi': 29, 'potato': 6, 'lead': 35, 'groundnut': 10, 'can': 3, 'fishmeal': 2, 'income': 12, 'palladium': 3, 'nickel': 11, 'lumber': 17, 'jet': 8, 'instal-debt': 5, 'dfl': 3, 'dmk': 14, 'stg': 17, 'coconut-oil': 7, 'corn-oil': 1, 'inventories': 6, 'cpu': 2, 'peseta': 1, 'austdlr': 4, 'cotton-oil': 3, 'naphtha': 7, 'nzdlr': 4, 'rand': 3, 'pork-belly': 3, 'ringgit': 1, 'coconut': 6, 'castorseed': 1, 'castor-oil': 2, 'lit': 3, 'rupiah': 1, 'skr': 1, 'nkr': 2, 'dkr': 1, 'sun-meal': 2, 'lin-meal': 1, 'cottonseed': 1, 'f-cattle': 3, 'bfr': 1, 'hk': 1, 'sfr': 3}

In [22]:
df_clean.shape[0]

10377

In [25]:
label_sum = 0

for key, value in sorted(dict_labels.items(), key=lambda x: x[1]):
    label_sum += value

print("Total label count:", label_sum)
print("Avg label count", label_sum / df_clean.shape[0])

Total label count: 13122
Avg label count 1.264527320034692

In [26]:
for key, value in sorted(dict_labels.items(), key=lambda x: x[1]): 
    print("{} : {}".format(key, value))

red-bean : 1
citruspulp : 1
rape-meal : 1
corn-oil : 1
peseta : 1
ringgit : 1
castorseed : 1
rupiah : 1
skr : 1
dkr : 1
lin-meal : 1
cottonseed : 1
bfr : 1
hk : 1
linseed : 2
lin-oil : 2
rye : 2
groundnut-oil : 2
cornglutenfeed : 2
wool : 2
fishmeal : 2
cpu : 2
castor-oil : 2
nkr : 2
sun-meal : 2
copra-cake : 3
palmkernel : 3
saudriyal : 3
can : 3
palladium : 3
dfl : 3
cotton-oil : 3
rand : 3
pork-belly : 3
lit : 3
f-cattle : 3
sfr : 3
plywood : 4
tapioca : 4
austdlr : 4
nzdlr : 4
instal-debt : 5
propane : 6
potato : 6
inventories : 6
coconut : 6
coconut-oil : 7
naphtha : 7
sun-oil : 8
rape-oil : 8
jet : 8
l-cattle : 9
groundnut : 10
platinum : 11
nickel : 11
income : 12
oat : 13
lei : 13
dmk : 14
tea : 15
sunseed : 17
lumber : 17
stg : 17
housing : 18
retail : 23
soy-oil : 25
heat : 25
orange : 25
soy-meal : 26
hog : 26
fuel : 28
wpi : 29
strategic-metal : 32
tin : 33
sorghum : 34
rapeseed : 35
lead : 35
silver : 36
pet-chem : 41
palm-oil : 42
zinc : 43
barley : 48
rubber : 49
meal-feed : 50
gas : 55
ipi : 57
alum : 58
yen : 58
cotton : 62
iron-steel : 65
rice : 67
cocoa : 68
jobs : 68
reserves : 73
carcass : 75
copper : 77
cpi : 101
bop : 101
soybean : 111
livestock : 112
money-supply : 126
nat-gas : 126
gold : 133
veg-oil : 136
coffee : 143
gnp : 153
dlr : 168
sugar : 175
oilseed : 182
corn : 224
wheat : 287
ship : 295
interest : 424
trade : 515
crude : 566
grain : 574
money-fx : 684
acq : 2210
earn : 3776

In [28]:
len(dict_labels.items())

119